theme: minima
title:  Ø
author: Pablo Cieslik
email: pablocieslik@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Pablo Cieslik Ø

# social links
twitter_username: narratario # DO NOT include the @ character, or else the build will fail!
github_username:  al-hum # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
